### PR TITLE
improve error handling when serial device not found

### PR DESCRIPTION
**Pull request by lancekindle**
Hey there,
When I run the following commands from within a python shell (with no arduino plugged in):
```
from pymata_aio.pymata3 import PyMata3
board = PyMata3()
```
I get this message before the python shell undesirably terminates.
> Unable to find Serial Port, Please plug in cable or check cable connections.

The python shell auto-terminating appears to be a result of pymata calling sys.exit(0)

If I put those above two commands into a script (example.py) and execute it with the -i  (interactive) flag for python, I see multiple errors, but stay within the shell.
`python3 -i example.py`

> Unable to find Serial Port, Please plug in cable or check cable connections.
> Traceback (most recent call last):
>   File "/home/lancey/.local/lib/python3.5/site-packages/serial/serialposix.py", line 289, in open
>     self.fd = os.open(self.portstr, os.O_RDWR|os.O_NOCTTY|os.O_NONBLOCK)
> FileNotFoundError: [Errno 2] No such file or directory: 'end'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/lancey/code/python/pymata-aio/pymata_aio/pymata_core.py", line 1685, in _discover_port
>     serialport = serial.Serial(device, 57600, timeout=0)
>   File "/home/lancey/.local/lib/python3.5/site-packages/serial/serialutil.py", line 282, in __init__
>     self.open()
>   File "/home/lancey/.local/lib/python3.5/site-packages/serial/serialposix.py", line 292, in open
>     raise SerialException(msg.errno, "could not open port %s: %s" % (self._port, msg))
> serial.serialutil.SerialException: [Errno 2] could not open port end: [Errno 2] No such file or directory: 'end'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "test.py", line 2, in <module>
>     b = PyMata3()
>   File "/home/lancey/code/python/pymata-aio/pymata_aio/pymata3.py", line 58, in __init__
>     com_port, ip_address, ip_port, ip_handshake)
>   File "/home/lancey/code/python/pymata-aio/pymata_aio/pymata_core.py", line 211, in __init__
>     self.com_port = self._discover_port()
>   File "/home/lancey/code/python/pymata-aio/pymata_aio/pymata_core.py", line 1699, in _discover_port
>     exit()
>   File "/home/lancey/bin/anaconda3/lib/python3.5/_sitebuiltins.py", line 26, in __call__
>     raise SystemExit(code)
> SystemExit: None
> >>>

This mess of errors is caused by sys.exit(0) being called inside the SerialException handling loop when the list of possible serial locations reaches 'end'.

So I removed 'end' from serial locations and moved the appropriate "Unable to find Serial Device..." to after the for-loop. Finally, I changed to sys.exit(0) to raise IOError() so that the python shell is not terminated.

### CODE REVIEW

**Comment by lancekindle** [comment]
I'm not familiar with asyncio.
Are sys.exit(0) exceptions necessary? I'd like to change more of the sys.exit(0) to a more specific Exception where possible

**Comment by MrYsLab** [comment]
@lancekindle Thank you for taking the time and submitting this pull request. Because this seems to be correcting a purely cosmetic issue in an edge development case (using the -i option), I feel it is too risky to incorporate into the code at this time.

What I would suggest is that you fork the code, make changes locally and then if there are any further releases, merge my changes back into your fork.

Please close this pull request.

**Comment by bendiken** [comment]
I wouldn't say @lancekindle's issue was purely cosmetic. I found it rather surprising that a library would ever dare to directly call `sys.exit()` in response to a non-fatal error condition that the caller of the library ought to get a chance to handle. As it is, at present there is no way to offer the end user a "retry" function in the application that calls PyMata, given that execution terminates on `SerialException` conditions.

**Comment by MrYsLab** [comment]
@bendiken You caught me, I am software daredevil. I beg to differ with you. If there is no serial communication then it is pointless to continue on, since there is no access to the Arduino board and hence, no "system". The cause of the failure is indeterminate and sometimes non-obvious (like not having the right sketch installed in the Arduino). If in the failure, the serial port is hung (which can happen with Leonardo's), a sketch cannot be uploaded using the Arduino IDE since the serial port is seen as in use. 
This is the safe approach and not a "daring" one.

**Comment by bendiken** [comment]
@MrYsLab I'm speaking specifically of the exit when there is no serial port device to be found (with autodetection, or with a supplied device string). The present approach makes it infeasible to e.g. write a GUI application where the user is given a chance to connect his device and retry the operation of connecting to it; the application will surprisingly just exit instead, and in the case of a GUI application not started from a terminal, without even an explanation of why.

Whether to exit the application or not (i.e., whether things are pointless or not) is not for software libraries to determine, it is for the application itself to determine. This is the separation between [mechanism and policy](https://en.wikipedia.org/wiki/Separation_of_mechanism_and_policy) (aka [the rule of separation](http://www.faqs.org/docs/artu/ch01s06.html)).

You already now have two indications, from @lancekindle and myself, of users expressing dismay at finding that this library dictates policy instead of merely providing mechanism. We are unlikely to be the only ones thus affected.

**Comment by MrYsLab** [comment]
[Here](https://github.com/MrYsLab/xibot) is a GUI based project that works without issue, so I am not sure what problems you are actually encountering. If you need your GUI to settle down before trying the serial connection, there is a [parameter](http://htmlpreview.github.io/?https://github.com/MrYsLab/pymata-aio/blob/master/documentation/html/pymata_core.html) called arduiino_wait that will delay things starting up. In addition, you can delay calling the start method when you are sure things are stable on your end.

What you are proposing may solve your problems, but will create problems for thousands of others. In order for me to even consider making changes, you would have to explain in detail or provide an example of why the mechanisms in place do not work for you.

**Pull request closed without merging**
